services:
  - type: web
    name: your-django-app
    env: python
    plan: free
    python:
      version: 3.11.8  # Explicit version specification
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: your-django-db
          property: connectionString
        
databases:
  - name: mindcraft
    databaseName: mindcraft
    user: mindcraft_user